language: python
python:
      - "3.5"
cache: pip
install:
      - pip install awscli
script:
    - aws s3 ls codelabs.se
deploy:
  provider: s3
  access_key_id: AKIAJG2X4TC47P4JGN6A
  secret_access_key:
    secure: pWB/S3tnqQayUXZCHoYGTjN+rqd00oRQ34ZMIKy+4spnajhV5I1+Sn9ChL4UaG3OAOF8k4vlUZ3vVcrDAsMPicauZysuJV52ci+82fEe19B9Kxid0LiUmhBxlmook8Uis8LfhjxDCv/mvqqbBwwm3pgMjKslURDAkevf34dt4oJWln571yKb97AQxku3pCHOGM0cbURrw8JzL9eI2dPn64kGwJE/QSIPXaRL3cZFppc1zkNc5IKhMIGGAgGirYnOsmVgv6dZcoNz4oGKPXRPGmsRX+aaw6PTP8eMcQt7JSkpxhEGvTupcscyIzm3CYzIfq1mmrLy2FKOZxz2bsB9xQPiNXqv3OB80b4Q+8cSKr+8zuKdARbiPhc4l+3P94NxgHjPAb8JbAjqt+R86XoZ+kzNBY+nEMGli6WQLo783vGd2RGvSHuEWWeHW/uGiePufonRp5m3YljRLOVR1h/fvZVwCoMYpu1hsL+KJ+fooFC2u4PO6VB2RSxJMxNCN3owrGfJCtte40HWdzG3wvAazKGzWX9rXbeUZU04Hk9xHxUBicvhpimdHxs2LZqduuQJPyl2IAXu2mY2whlyZBwesyeQiGH+Z9P6074RH2umok1YyWBT0kCGtHUJiWnbVe1+FTn1W/IKpPa+5Re4IXWiaJHFtaDfp+wTLtnML5eRhYQ=
  bucket: codelabs.se
  local-dir: .
  acl: public_read
  on:
    repo: codelabsab/web
    branch: codelabs.se
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id E2MSRD4XHMA41J --paths "/*html"
