language: python
python:
- '3.5'
cache: pip
install:
- pip install awscli
script:
- if [[ $TRAVIS_BRANCH =~ 'codelabs.se' ]]; then aws s3 ls $TRAVIS_BRANCH ||  exit(1); fi
deploy:
  provider: s3
  access_key_id: AKIAJG2X4TC47P4JGN6A
  secret_access_key:
    secure: pWB/S3tnqQayUXZCHoYGTjN+rqd00oRQ34ZMIKy+4spnajhV5I1+Sn9ChL4UaG3OAOF8k4vlUZ3vVcrDAsMPicauZysuJV52ci+82fEe19B9Kxid0LiUmhBxlmook8Uis8LfhjxDCv/mvqqbBwwm3pgMjKslURDAkevf34dt4oJWln571yKb97AQxku3pCHOGM0cbURrw8JzL9eI2dPn64kGwJE/QSIPXaRL3cZFppc1zkNc5IKhMIGGAgGirYnOsmVgv6dZcoNz4oGKPXRPGmsRX+aaw6PTP8eMcQt7JSkpxhEGvTupcscyIzm3CYzIfq1mmrLy2FKOZxz2bsB9xQPiNXqv3OB80b4Q+8cSKr+8zuKdARbiPhc4l+3P94NxgHjPAb8JbAjqt+R86XoZ+kzNBY+nEMGli6WQLo783vGd2RGvSHuEWWeHW/uGiePufonRp5m3YljRLOVR1h/fvZVwCoMYpu1hsL+KJ+fooFC2u4PO6VB2RSxJMxNCN3owrGfJCtte40HWdzG3wvAazKGzWX9rXbeUZU04Hk9xHxUBicvhpimdHxs2LZqduuQJPyl2IAXu2mY2whlyZBwesyeQiGH+Z9P6074RH2umok1YyWBT0kCGtHUJiWnbVe1+FTn1W/IKpPa+5Re4IXWiaJHFtaDfp+wTLtnML5eRhYQ=
  bucket: $TRAVIS_BRANCH
  local-dir: "."
  acl: public_read
  on:
    repo: codelabsab/web
    branch: $TRAVIS_BRANCH
after_deploy:
- if [[ $TRAVIS_BRANCH == 'codelabs.se' ]]; then aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id E2MSRD4XHMA41J --paths "/*html"; fi
env:
  global:
  - secure: qTbfbbwH6PSKVdDwfrAtLhBFBeijRBRgAum3gNGu/WKdMFE9sV/Ty0N6EnIMq+aDxK5yPh99EAWds1itXsT3Gx/6L6b+bXDUczxzjfvjU+lamBdjIOrX8RZ2plOJt9xbCHfdA/1DbiEJ0yyOTi0fObz66IzOMtEaTRr0+nkuxdgEa8F5fUZSWnxJmsb69CZy4LLtdq3a/08z/A3uFEhw7YmGOSVP8C42RGGXSC/8u7SarSjOlkW17XfcTqlIjAm3PgH+UW+6wfF+dq5gQBJeXA7xPXLA0LVVFw8OHRmKjwKiKP+rqNTT2a92ZngbMaESgmKWztSI2YlP/nMmmU/PXYUA1GclUy2x4QgOhASfbsFHRA4cwxfsHrK6IEsY0HKN87VWzjMQXPu4mLwx4271VnnXyg1GXzaCr7h4hCpJDVT9zjkv+gxBFqvN1+e+MRseegPmLb9t1y/0xDLsT7IswtJ2Z7gbJW/XUD8Jd+fRdlF0RgYHzjRFWG58Dlh404G6XIfv3MVBwLPEcT3VJqKD5j/Aakb3JyJPeVVzibO1hzUiLlNNAM+sHscO+Ne59JPx33NPgBQO9V211ntLJNmuC2wdLlmqbaiLChzFLtRTrgpEuBErV+FVA2i+rpSc2NCdj6NAhDOIqDr6EE1C2OilZRFuG8Z7zd8MehyDdMfmHdk=
  - secure: bT6rzWjucDqh6pIN2oejLXewqqcf+nQUSNF+0Cd8HGqzS2vTP812rxMPC80rs134K9XzhtTdjmZpAJ5NSW6Epn4W/c6TReKM/hFq7/HoD8Xl/YOPnTlf3AclvPkTx9PQ2zD6DAt1J8LHDDuHmsdd3iA7wWKBCzGhvEVfdAnQ+Myx1KU1mZe9cqibXAB5rC/y9+mTh9gACarGUDhFFFoonwJivQ0Bazuo4MIom/T6j49Wd4j8QuL5h48h8k+wUbolfjwDzTlaETSb7eL+kjoKeayM6+M+8Ymfxoe0KO7P3JykVa/XaxAtPrmsRuibUgLyeHM0lvPdg/ZyMsMxdc05DTv2oo+WW7bzBV8zaG3MJgXoxhcoole9q60XyHgHkB9tFAF+tq1fuJUrMfJAbBXSYZxD6NBmwEFt1ImwcZl2x/NY4iCWa1TfzWGHNK/xWvKua22ZSe5u73flRCTZBkpf+XFr/8MR75jgdPi+ouSFYvrTgXG7xhydmz/pExYPrkVWD0g33lIOFIMtCDwgQvkHCTBX6kLXV81OSKceQkWkDBYIvPiMLDk94JdYDEMsZ4fHrRsI1M3lUKCn0pppe1nnoVWCEUdwtrog8h1O0WCQ0aDw+9qKnrUBXY17kHcxvbeYCc4qK686T+JU/wCSurnn7rpKPw1BILuCH+C8XXZ/MQM=
notifications:
  slack:
    secure: HJHvn6wKNCIr3skGWx2HK8gz9KIdg8Yd73gBoUTyUgz39v16WkISHOVsSDDTg4RunX/nggO5XBwjc9HwZeiX2V4OjzAukOaufk/OOvz2Hl4vhkUIJWgho3KFJAcm+dOi3wwJHGFBtLW3yvprEnjIf6MQoQqsnXK21nzihgvO1kBS8UYagJvtFf0Tqhz3Biz1lcEJi5cTpkfaG9fCBit4qzQig5jZeBiVb2/aKiQYDhAvc6O9VijJj8TCCPWhPpQGAOUR+yjKZQGnSTmSEU1iJbvEngpmliARP3vAUS28Ahrw84C0LchdgBA3E1LcKxjZokRfaxKAHMEWg69ovufrwLoo6Eb6vLQR3qhvDrwrPV3zG7kgiiRStxtz2mjeAljcLqoKQ0BrUNxEEF4bHyVVAc5zpIalIWD/YzUw+WOrMcAA+Oti4XAbuD7tSoZrkqCutBmxonHLjITatGMzndKBMhHIJu5v7y77ibX1ZyRixBqZ/B9v+0HOEn61nZErlpy0L+TMRX/bWPyOFMqAQO6gz1mnEwwSeU/HBs020/yGrcAWCjU8bCukOJ8ax4fIpOSPgU3tKc5759I3YOE3s+QM4TWZ97CHk54c9t2nvW6sE0mZdjSIjVMW/5Rq4a9CIJaYnvgKjGgzq+rqlSugOxZL95gqBwQLqt3iHmpjNB54pto=
