---

- hosts: all
  become: yes
  tasks:
    - apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - nginx
        - php-fpm

    - synchronize:
        src: ../src/web/
        dest: /var/www/html

    - synchronize:
        src: ../src/nginx/
        dest: /etc/nginx/

    - copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
